# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{s3gb}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Michael Grosser"]
  s.date = %q{2010-06-09}
  s.default_executable = %q{s3gb}
  s.email = %q{grosser.michael@gmail.com}
  s.executables = ["s3gb"]
  s.files = [
    ".gitignore",
     "Rakefile",
     "Readme.md",
     "VERSION",
     "bin/s3gb",
     "lib/s3gb.rb",
     "lib/s3gb/base.rb",
     "lib/s3gb/jgit.rb",
     "lib/s3gb/s3fs.rb"
  ]
  s.homepage = %q{http://github.com/grosser/s3gb}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Backup stuff versioned in git to s3}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

